"""empty message

Revision ID: 156214c6ab22
Revises: 324e9f140ba0
Create Date: 2022-01-11 19:57:02.525511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156214c6ab22'
down_revision = '324e9f140ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labworkpass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'subject', 'studentid')
    )
    op.create_table('testpass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'studentid', 'subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testpass')
    op.drop_table('labworkpass')
    # ### end Alembic commands ###
