"""empty message

Revision ID: 16b633b417fd
Revises: 2f769836d23a
Create Date: 2022-01-11 19:51:56.810042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b633b417fd'
down_revision = '2f769836d23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'testdeadline', 'test', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    # ### end Alembic commands ###
