"""empty message

Revision ID: 1a17173f4e21
Revises: 3307352a12f2
Create Date: 2022-01-19 19:58:04.457286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a17173f4e21'
down_revision = '3307352a12f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=True)
    op.create_table('subject',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('edgroup',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('id', 'subject')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('id', 'subject')
    )
    op.create_table('assignedclass',
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('edgroup', 'subject')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('grants', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('edgroup', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_table('student')
    op.drop_table('assignedclass')
    op.drop_table('test')
    op.drop_table('labwork')
    op.drop_table('edgroup')
    op.drop_table('subject')
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
