"""empty message

Revision ID: 2f769836d23a
Revises: 4c9cd206c99c
Create Date: 2022-01-11 19:51:22.401601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f769836d23a'
down_revision = '4c9cd206c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testdeadline')
    # ### end Alembic commands ###
