"""empty message

Revision ID: 324e9f140ba0
Revises: cda8f56ebc73
Create Date: 2022-01-11 19:55:45.121206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324e9f140ba0'
down_revision = 'cda8f56ebc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'labworkdeadline', 'labwork', ['subject'], ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labworkdeadline', type_='foreignkey')
    # ### end Alembic commands ###
