"""empty message

Revision ID: 3307352a12f2
Revises: 64b8edfbb1c8
Create Date: 2022-01-19 19:54:41.250986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3307352a12f2'
down_revision = '64b8edfbb1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=True)
    op.create_table('subject',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('edgroup',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('id', 'subject'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('id', 'subject')
    )
    op.create_table('assignedclass',
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('edgroup', 'subject')
    )
    op.create_table('labworkdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('edgroupId', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edgroupId'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['id'], ['labwork.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['labwork.subject'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroupId')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('grants', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('edgroup', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['test.subject'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup')
    )
    op.create_table('labworkpass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['labwork.id'], ),
    sa.ForeignKeyConstraint(['studentid'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['labwork.subject'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'studentid')
    )
    op.create_table('testpass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['studentid'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['test.subject'], ),
    sa.PrimaryKeyConstraint('id', 'studentid', 'subject')
    )
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_table('testpass')
    op.drop_table('labworkpass')
    op.drop_table('testdeadline')
    op.drop_table('student')
    op.drop_table('labworkdeadline')
    op.drop_table('assignedclass')
    op.drop_table('test')
    op.drop_table('labwork')
    op.drop_table('edgroup')
    op.drop_table('subject')
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
