"""empty message

Revision ID: 3cc64f67f34a
Revises: 9e080ed904b3
Create Date: 2022-01-11 19:55:19.245940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc64f67f34a'
down_revision = '9e080ed904b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labworkdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('edgroupId', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['labwork.id'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroupId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labworkdeadline')
    # ### end Alembic commands ###
