"""empty message

Revision ID: 4403e969a1dc
Revises: b74de0f82df0
Create Date: 2022-01-11 19:58:04.966940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4403e969a1dc'
down_revision = 'b74de0f82df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'testpass', 'test', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testpass', type_='foreignkey')
    # ### end Alembic commands ###
