"""empty message

Revision ID: 44572a8ef0f9
Revises: 156214c6ab22
Create Date: 2022-01-11 19:57:25.431676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44572a8ef0f9'
down_revision = '156214c6ab22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'labworkpass', 'student', ['studentid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labworkpass', type_='foreignkey')
    # ### end Alembic commands ###
