"""edgroup tbl

Revision ID: 48c00b553329
Revises: f0425c1b7589
Create Date: 2022-01-11 17:31:29.924795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c00b553329'
down_revision = 'f0425c1b7589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edgroup',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edgroup')
    # ### end Alembic commands ###
