"""empty message

Revision ID: 4b20d66d904e
Revises: ddbf7bf1dfb0
Create Date: 2022-01-11 19:54:28.702714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b20d66d904e'
down_revision = 'ddbf7bf1dfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labworkdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('edgroupId', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edgroupId'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['id'], ['labwork.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['labwork.subject'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroupId')
    )
    op.create_unique_constraint(None, 'labwork', ['id'])
    op.create_unique_constraint(None, 'labwork', ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labwork', type_='unique')
    op.drop_constraint(None, 'labwork', type_='unique')
    op.drop_table('labworkdeadline')
    # ### end Alembic commands ###
