"""empty message

Revision ID: 64b8edfbb1c8
Revises: 3408df482fb0
Create Date: 2022-01-19 19:51:08.093436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b8edfbb1c8'
down_revision = '3408df482fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_id_key', 'test', type_='unique')
    op.drop_constraint('test_subject_key', 'test', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('test_subject_key', 'test', ['subject'])
    op.create_unique_constraint('test_id_key', 'test', ['id'])
    # ### end Alembic commands ###
