"""empty message

Revision ID: 663d6f13ccb9
Revises: e8eaa66931c7
Create Date: 2022-01-11 19:46:28.232897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663d6f13ccb9'
down_revision = 'e8eaa66931c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'test', ['id'])
    op.drop_constraint('testdeadline_subject_fkey', 'testdeadline', type_='foreignkey')
    op.create_foreign_key(None, 'testdeadline', 'test', ['id'], ['id'])
    op.create_foreign_key(None, 'testdeadline', 'edgroup', ['edgroup'], ['id'])
    op.create_foreign_key(None, 'testdeadline', 'test', ['subject'], ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    op.create_foreign_key('testdeadline_subject_fkey', 'testdeadline', 'subject', ['subject'], ['name'])
    op.drop_constraint(None, 'test', type_='unique')
    # ### end Alembic commands ###
