"""empty message

Revision ID: 69ba16f6fb1b
Revises: fe718470e28a
Create Date: 2022-01-20 15:20:59.227043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ba16f6fb1b'
down_revision = 'fe718470e28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labworkdeadline', sa.Column('edgroup', sa.String(length=10), nullable=False))
    op.create_foreign_key(None, 'labworkdeadline', 'edgroup', ['edgroup'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labworkdeadline', type_='foreignkey')
    op.drop_column('labworkdeadline', 'edgroup')
    # ### end Alembic commands ###
