"""empty message

Revision ID: 6b522d2fb577
Revises: 4e8e8b627835
Create Date: 2022-01-11 19:08:44.025884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b522d2fb577'
down_revision = '4e8e8b627835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labwork', sa.Column('subject', sa.String(length=100), nullable=False))
    op.drop_constraint('labwork_subject1_fkey', 'labwork', type_='foreignkey')
    op.create_foreign_key(None, 'labwork', 'subject', ['subject'], ['name'])
    op.drop_column('labwork', 'subject1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labwork', sa.Column('subject1', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'labwork', type_='foreignkey')
    op.create_foreign_key('labwork_subject1_fkey', 'labwork', 'subject', ['subject1'], ['name'])
    op.drop_column('labwork', 'subject')
    # ### end Alembic commands ###
