"""empty message

Revision ID: 7a2264f38477
Revises: 69ba16f6fb1b
Create Date: 2022-01-20 15:26:05.316309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2264f38477'
down_revision = '69ba16f6fb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labworkdeadline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labworkdeadline',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id', 'subject'], ['labwork.id', 'labwork.subject'], name='labworkdeadline_id_subject_fkey')
    )
    # ### end Alembic commands ###
