"""warn

Revision ID: 8b9dded365fb
Revises: 905759160ab0
Create Date: 2022-01-11 18:34:24.757437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9dded365fb'
down_revision = '905759160ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labwork', sa.Column('subject', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'labwork', 'subject', ['subject'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labwork', type_='foreignkey')
    op.drop_column('labwork', 'subject')
    # ### end Alembic commands ###
