"""empty message

Revision ID: 930df1f4815f
Revises: 9f5517f263e9
Create Date: 2022-01-11 19:30:06.716333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930df1f4815f'
down_revision = '9f5517f263e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('labwork')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labwork',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], name='labwork_subject_fkey'),
    sa.PrimaryKeyConstraint('id', name='labwork_pkey')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], name='test_subject_fkey')
    )
    # ### end Alembic commands ###
