"""empty message

Revision ID: 98155a891b1c
Revises: de71d9bdc2b3
Create Date: 2022-01-20 15:16:40.227780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98155a891b1c'
down_revision = 'de71d9bdc2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=True)
    op.add_column('labworkdeadline', sa.Column('edgroupId', sa.String(length=10), nullable=False))
    op.drop_constraint('labworkdeadline_edgroupid_fkey', 'labworkdeadline', type_='foreignkey')
    op.create_foreign_key(None, 'labworkdeadline', 'edgroup', ['edgroupId'], ['id'])
    op.drop_column('labworkdeadline', 'edgroupid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labworkdeadline', sa.Column('edgroupid', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'labworkdeadline', type_='foreignkey')
    op.create_foreign_key('labworkdeadline_edgroupid_fkey', 'labworkdeadline', 'edgroup', ['edgroupid'], ['id'])
    op.drop_column('labworkdeadline', 'edgroupId')
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    # ### end Alembic commands ###
