"""lw

Revision ID: 9d6cb56ab3a3
Revises: d404bc90ed71
Create Date: 2022-01-11 17:58:22.943894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6cb56ab3a3'
down_revision = 'd404bc90ed71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labwork')
    # ### end Alembic commands ###
