"""empty message

Revision ID: 9e080ed904b3
Revises: 4b20d66d904e
Create Date: 2022-01-11 19:54:54.033673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e080ed904b3'
down_revision = '4b20d66d904e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'labwork', ['id'])
    op.create_unique_constraint(None, 'labwork', ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labwork', type_='unique')
    op.drop_constraint(None, 'labwork', type_='unique')
    # ### end Alembic commands ###
