"""empty message

Revision ID: 9f5517f263e9
Revises: aee4b70dbc31
Create Date: 2022-01-11 19:16:57.605520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5517f263e9'
down_revision = 'aee4b70dbc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['test.id'], name='fk_testdl_test_id'),
    sa.ForeignKeyConstraint(['subject'], ['test.subject'], name='fk_testdl_test_subj'),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup')
    )
    op.alter_column('test', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'test', ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    op.alter_column('test', 'subject',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_table('testdeadline')
    # ### end Alembic commands ###
