"""empty message

Revision ID: a170ddb882ee
Revises: e3cec84f7e4a
Create Date: 2022-01-11 19:40:00.389056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a170ddb882ee'
down_revision = 'e3cec84f7e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'testdeadline', 'subject', ['subject'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    # ### end Alembic commands ###
