"""ac

Revision ID: a3b09cd90814
Revises: e5ec947e78e9
Create Date: 2022-01-11 17:56:42.854108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b09cd90814'
down_revision = 'e5ec947e78e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('assignedclass',
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('edgroup', 'subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignedclass')
    op.drop_table('subject')
    # ### end Alembic commands ###
