"""warn

Revision ID: b5e7bb53038d
Revises: 8c98a71dc98a
Create Date: 2022-01-11 18:00:37.363175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e7bb53038d'
down_revision = '8c98a71dc98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_deadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('edgroup', sa.String(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['test.subject'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup')
    )
    op.create_table('test_pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['studentid'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['test.subject'], ),
    sa.PrimaryKeyConstraint('id', 'studentid', 'subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_pass')
    op.drop_table('test_deadline')
    # ### end Alembic commands ###
