"""empty message

Revision ID: b74de0f82df0
Revises: 3abcd6539ff6
Create Date: 2022-01-11 19:57:55.500691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74de0f82df0'
down_revision = '3abcd6539ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'testpass', 'student', ['studentid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testpass', type_='foreignkey')
    # ### end Alembic commands ###
