"""empty message

Revision ID: cda8f56ebc73
Revises: 3cc64f67f34a
Create Date: 2022-01-11 19:55:33.158685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda8f56ebc73'
down_revision = '3cc64f67f34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'labworkdeadline', 'edgroup', ['edgroupId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labworkdeadline', type_='foreignkey')
    # ### end Alembic commands ###
