"""empty message

Revision ID: d1409b490756
Revises: 98155a891b1c
Create Date: 2022-01-20 15:19:11.459228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1409b490756'
down_revision = '98155a891b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=True)
    op.drop_constraint('labworkdeadline_edgroupid_fkey', 'labworkdeadline', type_='foreignkey')
    op.drop_column('labworkdeadline', 'edgroupid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labworkdeadline', sa.Column('edgroupid', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_foreign_key('labworkdeadline_edgroupid_fkey', 'labworkdeadline', 'edgroup', ['edgroupid'], ['id'])
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    # ### end Alembic commands ###
