"""empty message

Revision ID: d864f2b5a06b
Revises: e2758a2a97a5
Create Date: 2022-01-23 17:16:11.373049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd864f2b5a06b'
down_revision = 'e2758a2a97a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labwork', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('test', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name')
    op.drop_column('labwork', 'name')
    # ### end Alembic commands ###
