"""empty message

Revision ID: ddbf7bf1dfb0
Revises: 16b633b417fd
Create Date: 2022-01-11 19:52:54.775039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbf7bf1dfb0'
down_revision = '16b633b417fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'testdeadline', 'test', ['subject'], ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    # ### end Alembic commands ###
