"""empty message

Revision ID: de2614eb7fa1
Revises: d864f2b5a06b
Create Date: 2022-01-24 12:05:13.457851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2614eb7fa1'
down_revision = 'd864f2b5a06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('faculty', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subject', sa.Column('staffId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'staff', ['staffId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'staffId')
    op.drop_table('staff')
    # ### end Alembic commands ###
