"""empty message

Revision ID: de8b2e31aa77
Revises: 85b4108d6267
Create Date: 2022-01-11 19:33:33.861464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8b2e31aa77'
down_revision = '85b4108d6267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test', 'subject', ['subject'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    # ### end Alembic commands ###
