"""empty message

Revision ID: e2758a2a97a5
Revises: 9019c336ad95
Create Date: 2022-01-23 15:39:34.306249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2758a2a97a5'
down_revision = '9019c336ad95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'userId')
    # ### end Alembic commands ###
