"""empty message

Revision ID: e3cec84f7e4a
Revises: a3ff80ed22da
Create Date: 2022-01-11 19:39:24.912423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cec84f7e4a'
down_revision = 'a3ff80ed22da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup')
    )
    op.create_table('labwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('id', 'subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labwork')
    op.drop_table('testdeadline')
    # ### end Alembic commands ###
