"""empty message

Revision ID: e4c42f774800
Revises: 663d6f13ccb9
Create Date: 2022-01-11 19:47:42.958132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4c42f774800'
down_revision = '663d6f13ccb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testdeadline')
    op.create_unique_constraint(None, 'test', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    op.create_table('testdeadline',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('edgroup', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], name='testdeadline_subject_fkey'),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup', name='testdeadline_pkey')
    )
    # ### end Alembic commands ###
