"""empty message

Revision ID: e8eaa66931c7
Revises: a170ddb882ee
Create Date: 2022-01-11 19:45:34.478021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eaa66931c7'
down_revision = 'a170ddb882ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('testdeadline_subject_fkey', 'testdeadline', type_='foreignkey')
    op.create_foreign_key(None, 'testdeadline', 'edgroup', ['edgroup'], ['id'])
    op.create_foreign_key(None, 'testdeadline', 'test', ['id'], ['id'])
    op.create_foreign_key(None, 'testdeadline', 'test', ['subject'], ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    op.drop_constraint(None, 'testdeadline', type_='foreignkey')
    op.create_foreign_key('testdeadline_subject_fkey', 'testdeadline', 'subject', ['subject'], ['name'])
    # ### end Alembic commands ###
