"""empty message

Revision ID: ebc75c5d7fa3
Revises: 4403e969a1dc
Create Date: 2022-01-11 19:58:55.490123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc75c5d7fa3'
down_revision = '4403e969a1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'testpass', 'test', ['subject'], ['subject'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testpass', type_='foreignkey')
    # ### end Alembic commands ###
