"""empty message

Revision ID: ee99f4075e2a
Revises: 1a17173f4e21
Create Date: 2022-01-19 19:58:26.162104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee99f4075e2a'
down_revision = '1a17173f4e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testdeadline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('edgroup', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edgroup'], ['edgroup.id'], ),
    sa.ForeignKeyConstraint(['id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['test.subject'], ),
    sa.PrimaryKeyConstraint('id', 'subject', 'edgroup')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testdeadline')
    # ### end Alembic commands ###
