"""faculty table

Revision ID: f0425c1b7589
Revises: 19b7dc9afd80
Create Date: 2022-01-11 17:23:35.190417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0425c1b7589'
down_revision = '19b7dc9afd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_name'), 'faculty', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_name'), table_name='faculty')
    op.drop_table('faculty')
    # ### end Alembic commands ###
