"""lab2

Revision ID: fcfbc1a96e98
Revises: 1034debce589
Create Date: 2022-01-11 18:49:52.605949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfbc1a96e98'
down_revision = '1034debce589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject'], ['subject.name'], name='test_subject_fkey'),
    sa.PrimaryKeyConstraint('id', 'subject', name='test_pkey')
    )
    # ### end Alembic commands ###
